version: 2.1
jobs:
  preflight:
    working_directory: ~/ci
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint:
    working_directory: ~/ci
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: Running ESLint
          command: |
            mkdir -p ~/reports
            npx eslint ./src/ --format unix --output-file ~/reports/eslint.log
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  test:
    working_directory: ~/ci
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Running Jest tests
          command: npm test
  deploy:
    working_directory: ~/ci
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - add_ssh_keys:
          fingerprints:
            - "da:e8:9b:da:fe:4e:8e:7d:e9:f3:35:3f:56:06:76:40"
      - run:
          name: Building source in `production` mode
          command: npm run build:production
      - run:
          name: Copy `LICENSE`, `cd` into `dist` folder & make `CNAME`
          command: |
            cp ./LICENSE ./dist/LICENSE
            cd ./dist
            printf 'xbanki.me' > ./CNAME
            ls
      - run:
          name: Deploy build output to https://xbanki.me/
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            git init
            git remote add origin git@github.com:xbanki/xbanki.github.io.git
            git add *
            git commit -m "CI automatic deployment commit."
            git push origin master

workflows:
  deploy-gh-pages:
    jobs:
      - preflight:
          filters:
            branches:
              only: development
      - lint:
          requires:
            - preflight
      - test:
          requires:
            - preflight
      - deploy:
          requires:
            - lint
            - test